insert into pisu.commandcard (gameID, playerID, command, fieldType, cardIndex)
values  (15, 0, 'Again', 'PROGRAMMING', 2),
        (15, 0, 'Back 1', 'HAND', 0),
        (15, 0, 'Fast Fwd', 'HAND', 2),
        (15, 0, 'Fast Fwd', 'HAND', 4),
        (15, 0, 'Fast Fwd', 'PROGRAMMING', 0),
        (15, 0, 'Fwd', 'HAND', 5),
        (15, 0, 'Fwd 2', 'HAND', 6),
        (15, 0, 'Left OR Right', 'HAND', 7),
        (15, 0, 'null', 'HAND', 1),
        (15, 0, 'null', 'HAND', 3),
        (15, 0, 'null', 'PROGRAMMING', 1),
        (15, 0, 'null', 'PROGRAMMING', 3),
        (15, 0, 'null', 'PROGRAMMING', 4),
        (15, 1, 'Again', 'HAND', 5),
        (15, 1, 'Fast Fwd', 'HAND', 0),
        (15, 1, 'Fwd', 'HAND', 1),
        (15, 1, 'Left OR Right', 'HAND', 7),
        (15, 1, 'null', 'PROGRAMMING', 0),
        (15, 1, 'null', 'PROGRAMMING', 1),
        (15, 1, 'null', 'PROGRAMMING', 2),
        (15, 1, 'null', 'PROGRAMMING', 3),
        (15, 1, 'null', 'PROGRAMMING', 4),
        (15, 1, 'Turn Left', 'HAND', 2),
        (15, 1, 'Turn Left', 'HAND', 3),
        (15, 1, 'Turn Left', 'HAND', 4),
        (15, 1, 'Turn Right', 'HAND', 6);